# Generated by Django 4.1.4 on 2023-01-22 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auth_balance'),
        ('bike_and_terminal', '0019_rename_rent_rent_rent_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments_user',
            fields=[
                ('reciept_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.auth')),
            ],
        ),
        migrations.CreateModel(
            name='payments_bike',
            fields=[
                ('reciept_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('bike_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bike_and_terminal.bike')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.auth')),
            ],
        ),
    ]
