# Generated by Django 4.1.4 on 2023-01-22 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments_bike',
            old_name='reciept_no',
            new_name='receipt_no',
        ),
        migrations.RenameField(
            model_name='payments_user',
            old_name='reciept_no',
            new_name='receipt_no',
        ),
        migrations.AddField(
            model_name='payments_bike',
            name='cost',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='payments_user',
            name='cost',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='payments_bike',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='payments_user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
