# Generated by Django 4.1.4 on 2023-01-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_reciept_no_payments_bike_receipt_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments_bike',
            name='cost',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='payments_user',
            name='cost',
            field=models.CharField(default='', max_length=10),
        ),
    ]
