# Generated by Django 4.1.4 on 2023-01-24 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payments_bike_cost_alter_payments_user_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments_user',
            name='cardNo',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='payments_user',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
