# Generated by Django 4.1.4 on 2023-01-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_and_terminal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='terminal',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
