# Generated by Django 4.1.4 on 2023-01-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_and_terminal', '0004_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distance',
            old_name='dist',
            new_name='distance',
        ),
    ]
