# Generated by Django 4.1.4 on 2023-01-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_and_terminal', '0005_rename_dist_distance_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='distance',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
