# Generated by Django 4.1.4 on 2023-01-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_and_terminal', '0014_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='distance',
            field=models.CharField(max_length=20),
        ),
    ]
