# Generated by Django 4.1.4 on 2023-01-22 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike_and_terminal', '0016_remove_distance_distance_distance_enddistance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.CharField(max_length=10)),
                ('bike_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bike_and_terminal.bike')),
                ('term_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bike_and_terminal.terminal')),
            ],
        ),
    ]
