# Generated by Django 4.1.4 on 2023-01-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_and_terminal', '0017_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='term_id',
        ),
    ]
