# Generated by Django 4.1.4 on 2023-01-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike_and_terminal', '0018_remove_rent_term_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='rent',
            new_name='rent_cost',
        ),
    ]
