# Generated by Django 4.1.4 on 2023-01-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_and_terminal', '0019_rename_rent_rent_rent_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='fromt',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='rent',
            name='tot',
            field=models.CharField(default='', max_length=5),
        ),
    ]
