# Generated by Django 4.1.4 on 2023-01-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='terminal',
            new_name='admins',
        ),
    ]
