# Generated by Django 4.1.4 on 2023-01-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='auth',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('dl_num', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
