# Generated by Django 4.1.4 on 2023-01-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
